# Generated by Django 5.2.4 on 2025-09-04 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0008_remove_task_estimated_duration_task_reminder_minutes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_duration_minutes', models.PositiveIntegerField(help_text='AI estimated duration')),
                ('scheduled_date', models.DateField(help_text='Date when task is scheduled')),
                ('start_time', models.TimeField(help_text='Scheduled start time')),
                ('end_time', models.TimeField(help_text='Scheduled end time')),
                ('pomodoro_sessions', models.PositiveIntegerField(default=1, help_text='Number of 25-min sessions')),
                ('break_minutes', models.PositiveIntegerField(default=5, help_text='Break time between sessions')),
                ('ai_reasoning', models.TextField(help_text="DeepSeek's reasoning for this schedule")),
                ('priority_score', models.FloatField(help_text='Priority score from AI')),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='tasks.task')),
                ('time_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_tasks', to='tasks.timeblock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Scheduled Task',
                'verbose_name_plural': 'Scheduled Tasks',
                'ordering': ['scheduled_date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='DailySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_available_minutes', models.PositiveIntegerField()),
                ('total_scheduled_minutes', models.PositiveIntegerField()),
                ('total_break_minutes', models.PositiveIntegerField()),
                ('tasks_count', models.PositiveIntegerField(default=0)),
                ('moscow_must_count', models.PositiveIntegerField(default=0)),
                ('moscow_should_count', models.PositiveIntegerField(default=0)),
                ('ai_prompt_used', models.TextField(help_text='The prompt sent to DeepSeek')),
                ('ai_response', models.TextField(help_text='Full AI response')),
                ('generation_timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Schedule',
                'verbose_name_plural': 'Daily Schedules',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
