# Generated by Django 5.2.4 on 2025-09-05 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyschedule',
            name='ai_reasoning',
            field=models.TextField(blank=True, default='', help_text='AI reasoning for schedule decisions'),
        ),
        migrations.AddField(
            model_name='dailyschedule',
            name='generation_method',
            field=models.CharField(choices=[('ai', 'AI Generated'), ('custom', 'Custom Schedule'), ('manual', 'Manual Schedule')], default='custom', max_length=50),
        ),
        migrations.AddField(
            model_name='dailyschedule',
            name='moscow_could_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailyschedule',
            name='moscow_wont_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailyschedule',
            name='ai_prompt_used',
            field=models.TextField(blank=True, default='', help_text='The prompt sent to DeepSeek'),
        ),
        migrations.AlterField(
            model_name='dailyschedule',
            name='ai_response',
            field=models.TextField(blank=True, default='', help_text='Full AI response'),
        ),
    ]
