# Generated by Django 5.2.4 on 2025-09-05 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_dailyschedule_ai_reasoning_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledtask',
            name='schedule_type',
            field=models.CharField(choices=[('ai', 'AI Generated'), ('custom', 'Custom Schedule')], default='ai', help_text='Type of schedule that created this task', max_length=10),
        ),
    ]
