# Generated by Django 4.2.23 on 2025-09-02 03:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=1)),
                ('preferred_technique', models.CharField(choices=[('pomodoro', 'Pomodoro (25min work, 5min break)'), ('52_17', '52/17 Rule (52min work, 17min break)'), ('1_3_5', '1-3-5 Rule (1 big, 3 medium, 5 small tasks)')], default='pomodoro', max_length=20)),
                ('study_hours_per_day', models.IntegerField(default=4)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('streak_count', models.IntegerField(default=0)),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
