# Generated by Django 5.2.4 on 2025-09-03 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_firebaseuser_delete_firebaseaccount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FirebaseUser',
        ),
    ]
