# Generated by Django 5.2.4 on 2025-09-05 09:49

from django.db import migrations


def fix_study_hours_default(apps, schema_editor):
    """Fix any UserProfile records that might have null study_hours_per_day"""
    UserProfile = apps.get_model('accounts', 'UserProfile')
    
    # Update any profiles that have null study_hours_per_day
    UserProfile.objects.filter(study_hours_per_day__isnull=True).update(study_hours_per_day=4)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_delete_firebaseuser'),
    ]

    operations = [
        migrations.RunPython(fix_study_hours_default, migrations.RunPython.noop),
    ]
