# Generated by Django 5.2.4 on 2025-09-05 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20250905_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='study_hours_per_day',
            field=models.IntegerField(default=4),
        ),
    ]
