# Generated by Django 5.2.4 on 2025-09-02 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_completed_at_task_estimated_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='focus_category',
            field=models.CharField(blank=True, choices=[('', 'Not in Focus List'), ('big', '🎯 Big Thing (1)'), ('medium', '📋 Medium Thing (3)'), ('small', '✅ Small Thing (5)')], default='', help_text='Manually assign to 1-3-5 focus categories', max_length=10),
        ),
    ]
