# Generated by Django 5.2.4 on 2025-09-03 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_focus_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(max_length=20, choices=[
                ('work', 'Work'),
                ('personal', 'Personal'),
                ('study', 'Study'),
                ('health', 'Health'),
            ], default='work'),
        ),
    ]
