# Generated by Django 5.2.4 on 2025-09-03 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_task_assigned_to_alter_task_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('work', 'Work'), ('personal', 'Personal'), ('study', 'Study'), ('health', 'Health'), ('learning', 'Learning'), ('social', 'Social'), ('finance', 'Finance'), ('creative', 'Creative'), ('other', 'Other')], default='work', max_length=20),
        ),
    ]
