# Generated by Django 5.2.4 on 2025-09-04 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_task_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='estimated_duration',
        ),
        migrations.AddField(
            model_name='task',
            name='reminder_minutes',
            field=models.IntegerField(default=15, help_text='Minutes before due date to send reminder'),
        ),
    ]
