# Generated by Django 5.2.4 on 2025-09-04 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_remove_task_estimated_duration_task_reminder_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='pomodoro_sessions',
            field=models.IntegerField(default=1, help_text='Number of Pomodoro sessions needed'),
        ),
    ]
