# Generated by Django 5.2.4 on 2025-09-03 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
    ]
