# Generated by Django 5.2.5 on 2025-09-04 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20250903_2130'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('team_invite', 'Team Invitation'), ('task_assigned', 'Task Assigned'), ('task_status_change', 'Task Status Changed'), ('team_join', 'Team Member Joined'), ('task_due_reminder', 'Task Due Reminder'), ('team_task_update', 'Team Task Update')], max_length=20),
        ),
        migrations.CreateModel(
            name='NotificationPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_due_reminders', models.BooleanField(default=True)),
                ('weekly_summary', models.BooleanField(default=True)),
                ('team_updates', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
